services:
  php:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null  # Keep container running

  php74:
    image: php:7.4-cli
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null

  php80:
    image: php:8.0-cli
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null

  php81:
    image: php:8.1-cli
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null

  php82:
    image: php:8.2-cli
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null

  php83:
    image: php:8.3-cli
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null